kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind
nodes:
- role: control-plane
  image: m.daocloud.io/docker.io/kindest/node:v1.32.2
- role: worker
  image: m.daocloud.io/docker.io/kindest/node:v1.32.2
